name: hackathon-phoenix
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - pandas
  - numpy
  - swifter
  - matplotlib
  - optuna
  - scikit-learn
  - pip
  - pip:
      - pandas_profiling
      - autots
      - xgboost
      - lightgbm
      - tensorflow
